dist: xenial

language: clojure

node_js:
  - "11"

install: make deps

script: make travis-test

before_install:

# Retrieve Specific Version of Solc
- sudo wget --no-check-certificate -P /bin https://github.com/ethereum/solidity/releases/download/v0.5.8/solc-static-linux
- sudo chmod 775 /bin/solc-static-linux
- sudo ln -s /bin/solc-static-linx /usr/bin/solc

# Retrieve IPFS client
- wget https://dist.ipfs.io/ipfs-update/v1.5.2/ipfs-update_v1.5.2_linux-amd64.tar.gz
  -O ipfs-update.tar.gz
- tar -xzf ipfs-update.tar.gz

# Update to the latest IPFS client
- ipfs-update/ipfs-update install latest
- ipfs init

# Update Node Version through nvm
- nvm install 11.14.0
- nvm use 11.14.0

# Get ganache-cli commandline tool
- npm install -g ganache-cli

# Get truffle commandline tool
- npm install -g truffle

before_script:

# Deploy Truffle Migration
- make deploy

# Start ganache-cli as background process
- ganache-cli > /dev/null &

# Start IPFS Daemon as background process
- ipfs daemon > /dev/null &
